BASE_PATH = r"Scan_data_1\scan_data_{}.npy"
OUTPUT_PCD = "global_map_offline.pcd"
OUTPUT_OCCUPANCY_MAP = "realtime_occupancy_map.png"
START_FILE = 1
END_FILE = 1800
save_dir = r"camera_data"
RESOLUTION_MM_PER_PIXEL = 30# độ phân giải (1 pixel = 30 mm)
MAP_WIDTH_MM = 30000
MAP_HEIGHT_MM = 25000
ICP_VOXEL_SIZE = 25.0
ICP_THRESHOLD = 180.0
MAX_RMSE_THRESHOLD = 50.0#ngưỡng tối đa 
OUTLIER_NB_NEIGHBORS = 30
OUTLIER_STD_RATIO = 1.5
DUPLICATE_VOXEL_SIZE = 30.0
DYNAMIC_DISTANCE_THRESHOLD = 300.0
LOCAL_MAP_RADIUS_MM = 9000.0 # Bán kính để tạo bản đồ cục bộ cho ICP
MIN_ICP_MAP_POINTS = 50 # Số điểm tối thiểu cho bản đồ cục bộ ICP, nếu không đủ sẽ dùng toàn bộ bản đồ
ROBOT_AXIS_LENGTH_MM = 300                                                                                                               
DELAY_MS = 20
IMG_SIZE = 1200
MAP_WIDTH_PIXELS = int(MAP_WIDTH_MM / RESOLUTION_MM_PER_PIXEL)
MAP_HEIGHT_PIXELS = int(MAP_HEIGHT_MM / RESOLUTION_MM_PER_PIXEL)
GICP_VOXEL_SIZE = 20
CAMERA_TRIGGER_DISTANCE_MM = 1000.0 # Ngưỡng khoảng cách (mm) để bật camera
MAP_MAINTENANCE_INTERVAL = 10 # Số frame trước khi dọn dẹp bản đồ toàn cục (downsample, prune)
f= 381.0
cx =320.0
cy= 240.0
B =26.0